"""
ml_core/scoring/feynman_scorer.py

Scores a learner's Feynman-style explanation against ml_core/scoring/rubrics/feynman_v1.yaml.

Why this uses client.messages.parse(), not the streaming/text-prompt
pattern used elsewhere in ml_core:
The JS prototypes (career.js, academic.js) asked Claude to "return ONLY
valid JSON" in a text prompt and stripped markdown fences from the
response — fragile, and silently wrong if the model adds a stray sentence
before the JSON. messages.parse(output_format=PydanticModel) makes the API
itself enforce a JSON schema and gives back a validated Pydantic instance
directly — no manual parsing, no fence-stripping, no hoping the model
behaved. This is strictly more robust and is used for every scoring call
in ml_core (Feynman here, quiz generation next).

Why the model returns per-dimension scores + rationale, but NOT an overall
score:
Per the strategy doc's Risk #2 ("rubric-and-rationale output, never a bare
number"): the composite score is a deterministic weighted sum, computed in
Python from the rubric's fixed weights (see rubric_loader.py), not
generated by the model. This means the formula is auditable, can't
silently drift between calls, and the eval harness can recompute it from
raw dimension scores to check for rubric/weight regressions independently
of whether the MODEL's per-dimension judgment changed.
"""

from __future__ import annotations

import os
import time
from dataclasses import dataclass

try:
    import anthropic
    from anthropic import (
        APIConnectionError,
        APITimeoutError,
        RateLimitError,
        OverloadedError,
        AuthenticationError,
        BadRequestError,
        AnthropicError,
    )
    from pydantic import BaseModel, Field
except ImportError:
    anthropic = None
    BaseModel = object  # type: ignore

from ml_core.scoring.rubric_loader import load_rubric, band_for_score, Rubric

DEFAULT_MODEL = "claude-sonnet-4-5"
MAX_RETRIES = 3
BASE_BACKOFF_SECONDS = 1.5

_RETRYABLE_ERRORS = (RateLimitError, APIConnectionError, APITimeoutError, OverloadedError) if anthropic else ()


class ScoringError(Exception):
    """Raised for scoring failures that are NOT worth retrying, or for
    retries exhausted. Always carries a specific reason."""


# ── Structured output schema ───────────────────────────────────────────────
# This Pydantic model IS the JSON schema sent to Claude via output_format.
# Field descriptions are part of the schema the model sees, not just
# Python documentation — keep them instructive, since they function as
# part of the prompt.

if anthropic is not None:

    class DimensionScore(BaseModel):
        score: float = Field(
            ge=0.0, le=1.0,
            description="Score from 0.0 to 1.0 for this dimension, following the rubric's scoring guide bands exactly."
        )
        rationale: str = Field(
            description="One specific sentence justifying this score — cite what the explanation did or didn't do, not a generic restatement of the score band."
        )

    class FeynmanScoreOutput(BaseModel):
        accuracy: DimensionScore
        clarity: DimensionScore
        depth: DimensionScore
        transfer: DimensionScore

else:
    DimensionScore = None  # type: ignore
    FeynmanScoreOutput = None  # type: ignore


@dataclass
class FeynmanResult:
    overall: float
    band: str  # "needs_work" | "developing" | "solid" | "excellent"
    dimensions: dict[str, dict]  # {"accuracy": {"score": 0.8, "rationale": "..."}, ...}
    rubric_version: str


def _get_client() -> "anthropic.Anthropic":
    if anthropic is None:
        raise ScoringError(
            "anthropic package is not installed. Run `pip install anthropic` to enable scoring."
        )
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise ScoringError("ANTHROPIC_API_KEY is not set. Add it to your .env — scoring cannot run without it.")
    return anthropic.Anthropic(api_key=api_key, max_retries=0)


def _build_scoring_prompt(rubric: Rubric, topic: str, explanation: str) -> str:
    dimension_blocks = []
    for d in rubric.dimensions:
        guide_lines = "\n".join(f"  {rng}: {desc}" for rng, desc in d.scoring_guide.items())
        dimension_blocks.append(f"### {d.name} (weight {d.weight})\n{d.description.strip()}\nScoring guide:\n{guide_lines}")

    rubric_text = "\n\n".join(dimension_blocks)

    return f"""You are evaluating a learner's Feynman-style explanation of a concept — they were asked to explain it as if teaching a curious 12-year-old, without their source notes visible.

Topic: "{topic}"

Learner's explanation:
\"\"\"
{explanation}
\"\"\"

Score this explanation on each of the following dimensions, strictly following the scoring guide bands given for each one. Do not be lenient — most explanations from real learners score in the 0.4-0.7 range on a first attempt; reserve 0.85+ for explanations that genuinely meet the top band's description.

{rubric_text}

For each dimension, give a score from 0.0 to 1.0 and a one-sentence rationale that cites something SPECIFIC the explanation did or didn't do — not a generic restatement of the score band's wording."""


def _retry_call(fn, *args, **kwargs):
    last_error: Exception | None = None
    for attempt in range(MAX_RETRIES):
        try:
            return fn(*args, **kwargs)
        except _RETRYABLE_ERRORS as e:
            last_error = e
            if attempt < MAX_RETRIES - 1:
                time.sleep(BASE_BACKOFF_SECONDS * (2 ** attempt))
            continue
        except AuthenticationError as e:
            raise ScoringError(f"Claude API authentication failed — check ANTHROPIC_API_KEY: {e}") from e
        except BadRequestError as e:
            raise ScoringError(f"Claude API rejected the scoring request: {e}") from e
        except AnthropicError as e:
            raise ScoringError(f"Claude API error during scoring: {e}") from e
    raise ScoringError(f"Scoring failed after {MAX_RETRIES} retries. Last error: {last_error}")


def score_feynman_explanation(
    topic: str,
    explanation: str,
    rubric_name: str = "feynman_v1",
    model: str = DEFAULT_MODEL,
) -> FeynmanResult:
    """
    Scores a Feynman explanation against the named rubric. Raises
    ScoringError if the explanation is empty/too short to meaningfully
    score, or if the API call fails after retries.
    """
    if not explanation or len(explanation.strip()) < 20:
        raise ScoringError(
            "Explanation is too short to score meaningfully (< 20 characters). "
            "Ask the learner to write a real explanation, not a one-word answer."
        )

    rubric = load_rubric(rubric_name)
    client = _get_client()
    prompt = _build_scoring_prompt(rubric, topic, explanation)

    def _call():
        response = client.messages.parse(
            model=model,
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
            output_format=FeynmanScoreOutput,
        )
        return response.parsed_output

    parsed: "FeynmanScoreOutput" = _retry_call(_call)

    if parsed is None:
        raise ScoringError("Claude did not return a parseable structured score for this explanation.")

    dimension_results = {}
    composite = 0.0
    for dim in rubric.dimensions:
        dim_score: DimensionScore = getattr(parsed, dim.name)
        dimension_results[dim.name] = {"score": dim_score.score, "rationale": dim_score.rationale}
        composite += dim_score.score * dim.weight

    band = band_for_score(rubric, composite)

    return FeynmanResult(
        overall=round(composite, 4),
        band=band,
        dimensions=dimension_results,
        rubric_version=rubric.version,
    )